const data = [
  {
    "Timestamp": "11/30/2017 20:44:41",
    "experience": "15+",
    "size": "100+",
    "salary": "$110,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Sr Software Enginner",
    "skills": "java, web services",
    "work": "I work remotely",
    "education": "Bachelors",
    "degree": "BS Electrical Engineering, minors math & cs "
  },
  {
    "Timestamp": "11/30/2017 20:59:23",
    "experience": "4-6",
    "size": "50-100",
    "salary": "$112,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Senior Software Engineer",
    "skills": "Ruby, JavaScript, Java, RabbitMQ",
    "work": "I work remotely",
    "education": "Bachelors",
    "degree": "Literature"
  },
  {
    "Timestamp": "11/30/2017 21:04:20",
    "experience": "2-4",
    "size": "1-5",
    "salary": "$60,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "CEO",
    "skills": "Javascript",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "11/30/2017 21:05:08",
    "experience": "6-8",
    "size": "10-50",
    "salary": "$110,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Front End Engineer",
    "skills": "Javascript, Node, Laravel, MySQL, NoSQL,  React, Redux, Ember",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "11/30/2017 21:14:16",
    "experience": "4-6",
    "size": "100+",
    "salary": "$91,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Developer",
    "skills": "PHP, JavaScript, Python, Ruby, Elm, Java, Node, Golang",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "11/30/2017 21:28:40",
    "experience": "6-8",
    "size": "1-5",
    "salary": "$60,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Developer",
    "skills": "Javascript, Java, PHP, Android",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": "Information Technology"
  },
  {
    "Timestamp": "11/30/2017 21:40:42",
    "experience": "15+",
    "size": "10-50",
    "salary": "$130,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Director (Senior Dev or something)",
    "skills": "SQL, Elixir, Ruby, JavaScript, Java, etc, etc.",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": ""
  },
  {
    "Timestamp": "11/30/2017 21:44:29",
    "experience": "4-6",
    "size": "100+",
    "salary": "$115,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Developer",
    "skills": "JavaScript, C#, Java, Kotlin, SQL, React, docker, Git",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Mathematics"
  },
  {
    "Timestamp": "11/30/2017 21:48:36",
    "experience": "0-1",
    "size": "1-5",
    "salary": "$49,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Front End Developer",
    "skills": "Javascript",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "11/30/2017 22:08:57",
    "experience": "10-15",
    "size": "10-50",
    "salary": "$98,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Engineer",
    "skills": "JavaScript iOS java sql",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "11/30/2017 23:31:54",
    "experience": "2-4",
    "size": "100+",
    "salary": "$83,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Developer",
    "skills": "JavaScript, CSS, Java, React, Angular",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Mathematics"
  },
  {
    "Timestamp": "12/1/2017 0:22:30",
    "experience": "4-6",
    "size": "10-50",
    "salary": "$65,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Consultant",
    "skills": "C#, JS, SQL",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "12/1/2017 2:36:08",
    "experience": "2-4",
    "size": "6-10",
    "salary": "$90,000.00",
    "happy": 1,
    "gender": "Male",
    "position": "Principal Engineer",
    "skills": "Node, Go, AWS, React",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "IT"
  },
  {
    "Timestamp": "12/1/2017 7:21:03",
    "experience": "2-4",
    "size": "6-10",
    "salary": "$55,000.00",
    "happy": 3,
    "gender": "Female",
    "position": "Application Designer and Developer",
    "skills": "Front End Development, UI/UX Design/ CSS/SCSS/HTML, JavaScript, React",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Bachelor of Fine Arts in Digital Art with Computer Science Minor"
  },
  {
    "Timestamp": "12/1/2017 7:51:39",
    "experience": "15+",
    "size": "10-50",
    "salary": "$120,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Senior Software Developer",
    "skills": "Ruby/JS/SQL",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Information Technology/Accounting"
  },
  {
    "Timestamp": "12/1/2017 8:24:03",
    "experience": "10-15",
    "size": "100+",
    "salary": "$102,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Senior Software Developer",
    "skills": "Go, C, C++, Ruby, Perl, Design/Architecture, Ops",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "12/1/2017 8:35:01",
    "experience": "4-6",
    "size": "1-5",
    "salary": "$75,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "CEO",
    "skills": "Name it.",
    "work": "Work at a company in or around Cincinnati",
    "education": "Masters",
    "degree": "AI"
  },
  {
    "Timestamp": "12/1/2017 8:40:39",
    "experience": "2-4",
    "size": "100+",
    "salary": "$57,000.00",
    "happy": 3,
    "gender": "Female",
    "position": "Software Developer",
    "skills": "Python/Django, C#/.NET",
    "work": "Work at a company in or around Cincinnati",
    "education": "Masters",
    "degree": "Spanish & Biology"
  },
  {
    "Timestamp": "12/1/2017 8:52:24",
    "experience": "2-4",
    "size": "50-100",
    "salary": "$65,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Mobile Native Developer",
    "skills": "Objective-C, Swift, HTML, JavaScript, Alexa Skill Development, Jenkins CI",
    "work": "Just moved to Cleveland from Cinci ",
    "education": "Bachelors",
    "degree": "Kinesiology "
  },
  {
    "Timestamp": "12/1/2017 8:54:44",
    "experience": "8-10",
    "size": "10-50",
    "salary": "$105,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Senior Developer",
    "skills": "php, ruby, javascript, python, sass/less/css, html, sql",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Information Technology"
  },
  {
    "Timestamp": "12/1/2017 9:09:33",
    "experience": "4-6",
    "size": "6-10",
    "salary": "$75,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Application Engineer",
    "skills": "Javascript, CSS, HTML",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": "Information Technology"
  },
  {
    "Timestamp": "12/1/2017 9:19:53",
    "experience": "8-10",
    "size": "100+",
    "salary": "$82,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Mobile Team Lead",
    "skills": "Java, .NET, C#, Kotlin, many others",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Information Systems"
  },
  {
    "Timestamp": "12/1/2017 9:24:56",
    "experience": "4-6",
    "size": "100+",
    "salary": "$103,000.00",
    "happy": 4,
    "gender": "Female",
    "position": "Senior Software Developer",
    "skills": "Ruby, Rails, Javascript, React",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science and Engineering"
  },
  {
    "Timestamp": "12/1/2017 9:27:22",
    "experience": "10-15",
    "size": "100+",
    "salary": "$104,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Director",
    "skills": "PHP, Javascript, React, Laravel, Go, AWS, Node, Webpack",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Information Science"
  },
  {
    "Timestamp": "12/1/2017 10:02:48",
    "experience": "2-4",
    "size": "10-50",
    "salary": "$55,000.00",
    "happy": 4,
    "gender": "Female",
    "position": "Web Developer",
    "skills": "HTML/CSS, JS, Python, Java, MongoDB",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Biology"
  },
  {
    "Timestamp": "12/1/2017 10:05:04",
    "experience": "0-1",
    "size": "10-50",
    "salary": "$59,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Front End Developer / UX and UI",
    "skills": "Ruby, Javascript",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "12/1/2017 10:19:01",
    "experience": "15+",
    "size": "6-10",
    "salary": "$150,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Director",
    "skills": "Ruby, Javascript, Java",
    "work": "I work remotely",
    "education": "Masters",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "12/1/2017 10:23:40",
    "experience": "2-4",
    "size": "100+",
    "salary": "$58,000.00",
    "happy": 3,
    "gender": "Male",
    "position": "Software Developer",
    "skills": "Python, C#, Java, JavaScript",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Information Technology"
  },
  {
    "Timestamp": "12/1/2017 10:35:44",
    "experience": "15+",
    "size": "10-50",
    "salary": "$125,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Software Developer",
    "skills": "Polyglot",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Engineering"
  },
  {
    "Timestamp": "12/1/2017 10:38:46",
    "experience": "4-6",
    "size": "100+",
    "salary": "$85,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Software Engineer",
    "skills": "Javascript",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "12/1/2017 10:50:04",
    "experience": "4-6",
    "size": "10-50",
    "salary": "$84,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "developer",
    "skills": "Ruby, Python, PHP, Javascript, etc etc",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "12/1/2017 10:56:19",
    "experience": "6-8",
    "size": "6-10",
    "salary": "$65,000.00",
    "happy": 5,
    "gender": "Female",
    "position": "Frontend Developer",
    "skills": "JS, HTML, CSS",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Electronic Media"
  },
  {
    "Timestamp": "12/1/2017 10:58:44",
    "experience": "15+",
    "size": "10-50",
    "salary": "$115,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Lead Developer",
    "skills": "JS, PHP, Ruby",
    "work": "Work at a company in or around Cincinnati",
    "education": "Masters",
    "degree": "CompE, CS"
  },
  {
    "Timestamp": "12/1/2017 12:10:08",
    "experience": "0-1",
    "size": "10-50",
    "salary": "$50,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Junior PHP developer",
    "skills": "PHP, MySQL",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": "Web/Computer programming"
  },
  {
    "Timestamp": "12/1/2017 12:19:25",
    "experience": "2-4",
    "size": "100+",
    "salary": "$72,000.00",
    "happy": 3,
    "gender": "Female",
    "position": "SFCC developer",
    "skills": "html5, css3, javascript, jquery, SFCC, sass, gulp, grunt",
    "work": "I work remotely",
    "education": "Bachelors",
    "degree": "photography"
  },
  {
    "Timestamp": "12/1/2017 12:40:27",
    "experience": "6-8",
    "size": "1-5",
    "salary": "$52,000.00",
    "happy": 4,
    "gender": "Female",
    "position": "Marketing Manager",
    "skills": "CSS, Basic HTML, Wordpress, Adobe Creative Suite",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Design Studies"
  },
  {
    "Timestamp": "12/1/2017 13:23:48",
    "experience": "10-15",
    "size": "1-5",
    "salary": "$24,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Co-Founder + CTO",
    "skills": "Python, Ruby, C#, C++, Java, Swift, Javascript, HTML/CSS",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "12/1/2017 13:32:15",
    "experience": "4-6",
    "size": "10-50",
    "salary": "$85,000.00",
    "happy": 5,
    "gender": "Female",
    "position": "Designer + Front End Developer + Director of HR",
    "skills": "HTML, CSS, Javascript, React, ReactNative",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Bachelor of Science in Design"
  },
  {
    "Timestamp": "12/1/2017 14:03:07",
    "experience": "4-6",
    "size": "100+",
    "salary": "$62,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Jr Web Developer",
    "skills": "PHP, HTML, CSS, JS, SQL",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "12/1/2017 14:39:07",
    "experience": "2-4",
    "size": "10-50",
    "salary": "$78,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Software Developer",
    "skills": "JavaScript, TypeScript, Elixir, Ruby, C#",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Humanities"
  },
  {
    "Timestamp": "12/1/2017 15:17:25",
    "experience": "2-4",
    "size": "10-50",
    "salary": "$70,000.00",
    "happy": 3,
    "gender": "Male",
    "position": "Software Developer",
    "skills": "Full Stack .Net, JQuery, HTML, CSS, Java",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "12/1/2017 18:29:48",
    "experience": "15+",
    "size": "100+",
    "salary": "$115,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Lead dev",
    "skills": "hadoop, java, python",
    "work": "Work at a company in or around Cincinnati",
    "education": "Masters",
    "degree": "computer science"
  },
  {
    "Timestamp": "12/1/2017 18:57:28",
    "experience": "Still in school",
    "size": "100+",
    "salary": "$22,500.00",
    "happy": 4,
    "gender": "Male",
    "position": "Software Developer Coop",
    "skills": "c++, java, js, c#",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": "Computer Engineering"
  },
  {
    "Timestamp": "12/1/2017 19:04:50",
    "experience": "2-4",
    "size": "6-10",
    "salary": "$67,000.00",
    "happy": 3,
    "gender": "Male",
    "position": "UX/Front-end",
    "skills": "HTML,CSS,UX,design",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": ""
  },
  {
    "Timestamp": "12/1/2017 19:19:17",
    "experience": "10-15",
    "size": "100+",
    "salary": "$120,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Software Developer",
    "skills": "JavaScript, HTML, CSS, Java, Python ...",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Information Systems"
  },
  {
    "Timestamp": "12/1/2017 21:35:42",
    "experience": "8-10",
    "size": "100+",
    "salary": "$80,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Software Developer",
    "skills": ".Net, C#, SQL, ColdFusion, JavaScript,  jQuery and some angular/ react framework exposure. IIS. ",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Information Engineering Technology"
  },
  {
    "Timestamp": "12/2/2017 10:24:46",
    "experience": "15+",
    "size": "10-50",
    "salary": "$125,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Principal Consultant",
    "skills": "Java, others",
    "work": "Work at a company in or around Cincinnati",
    "education": "Masters",
    "degree": "Computer Engineering"
  },
  {
    "Timestamp": "12/2/2017 12:25:57",
    "experience": "10-15",
    "size": "100+",
    "salary": "$125,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Senior Software Engineer",
    "skills": "Java, Javascript, React, Backbone",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Information Systems"
  },
  {
    "Timestamp": "12/2/2017 22:29:38",
    "experience": "4-6",
    "size": "10-50",
    "salary": "$85,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Software Developer",
    "skills": "C#, Apex, JS, Web Development, Salesforce",
    "work": "I work remotely",
    "education": "Masters",
    "degree": "Computer information Systems"
  },
  {
    "Timestamp": "12/3/2017 5:22:13",
    "experience": "6-8",
    "size": "100+",
    "salary": "$73,500.00",
    "happy": 5,
    "gender": "Male",
    "position": "Python developer",
    "skills": "Python, Django, AWS, GIT",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer science"
  },
  {
    "Timestamp": "12/3/2017 10:14:28",
    "experience": "2-4",
    "size": "50-100",
    "salary": "$60,000.00",
    "happy": 3,
    "gender": "Male",
    "position": "Dev",
    "skills": "Java, gwt, app engine, cloud data store",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": "Software Engineering "
  },
  {
    "Timestamp": "12/3/2017 10:25:02",
    "experience": "0-1",
    "size": "50-100",
    "salary": "$51,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Front end developer",
    "skills": "HTML, css, JavaScript ",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Political science "
  },
  {
    "Timestamp": "12/3/2017 12:10:35",
    "experience": "10-15",
    "size": "100+",
    "salary": "$113,345.00",
    "happy": 4,
    "gender": "Male",
    "position": "DevOps Engineer ",
    "skills": "C#, TypeScript, PowerShell, Bash, Groovy, Java",
    "work": "Work at a company in or around Cincinnati",
    "education": "Masters",
    "degree": "MBA"
  },
  {
    "Timestamp": "12/3/2017 22:28:04",
    "experience": "10-15",
    "size": "100+",
    "salary": "$85,000.00",
    "happy": 3,
    "gender": "Female",
    "position": "Sr. Developer",
    "skills": "Java, AngularJS",
    "work": "Work at a company in or around Cincinnati",
    "education": "Doctorate",
    "degree": "Physics"
  },
  {
    "Timestamp": "12/4/2017 7:56:34",
    "experience": "0-1",
    "size": "100+",
    "salary": "$65,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Developer",
    "skills": "Js, Java",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "12/4/2017 9:52:54",
    "experience": "8-10",
    "size": "10-50",
    "salary": "$120,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Senior Software Engineer",
    "skills": "Java, Kotlin, Docker, Gradle, Spring, Play",
    "work": "Based in SF with small office in Blue Ash",
    "education": "Bachelors",
    "degree": "Management"
  },
  {
    "Timestamp": "12/4/2017 10:34:57",
    "experience": "10-15",
    "size": "10-50",
    "salary": "$140,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Partner",
    "skills": "Java, Kotlin, Android, Spring",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "12/4/2017 12:16:14",
    "experience": "10-15",
    "size": "1-5",
    "salary": "$60,000.00",
    "happy": 3,
    "gender": "Male",
    "position": "Frontend Developer/CMS Guru",
    "skills": "html, css, js, php, mysql, WordPress, ExpressionEngine, SEO",
    "work": "I work remotely",
    "education": "Bachelors",
    "degree": "CSCI"
  },
  {
    "Timestamp": "12/4/2017 12:46:52",
    "experience": "2-4",
    "size": "50-100",
    "salary": "$65,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Consultant",
    "skills": "JavaScript, C#, Selenium",
    "work": "Work at a company in or around Cincinnati",
    "education": "Masters",
    "degree": "Masters of Fine Arts in Writing"
  },
  {
    "Timestamp": "12/4/2017 13:14:29",
    "experience": "15+",
    "size": "1-5",
    "salary": "$75,700.00",
    "happy": 3,
    "gender": "Female",
    "position": "Sr. consultant",
    "skills": "Multi value database, basic, JavaScript,. Php",
    "work": "I work remotely",
    "education": "Masters",
    "degree": "Master of Library Science, BABA Information Systems"
  },
  {
    "Timestamp": "12/4/2017 16:53:25",
    "experience": "4-6",
    "size": "10-50",
    "salary": "$80,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Engineer",
    "skills": "HTML, Javascript, CSS,",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "12/4/2017 22:46:55",
    "experience": "0-1",
    "size": "10-50",
    "salary": "$55,000.00",
    "happy": 2,
    "gender": "Male",
    "position": "Software Developer",
    "skills": "Java, HTML, CSS, SQL, database design, UI design, UX design",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "12/4/2017 22:50:01",
    "experience": "15+",
    "size": "10-50",
    "salary": "$135,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Principal Consultant",
    "skills": "Java, C++",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "12/4/2017 23:43:04",
    "experience": "8-10",
    "size": "10-50",
    "salary": "$72,000.00",
    "happy": 3,
    "gender": "Male",
    "position": "Senior Development",
    "skills": "Elixir, JavaScript, Java, Scala, Elm",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Software Development"
  },
  {
    "Timestamp": "12/5/2017 10:44:49",
    "experience": "2-4",
    "size": "10-50",
    "salary": "$73,000.00",
    "happy": 5,
    "gender": "Female",
    "position": "Front End Engineer",
    "skills": "React, JavaScript, HTML, CSS",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": "Web Design"
  },
  {
    "Timestamp": "12/5/2017 10:56:56",
    "experience": "4-6",
    "size": "100+",
    "salary": "$87,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Software Engineer 3",
    "skills": "Javascript, Java, Kotlin, React, Angular ",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "12/5/2017 18:20:30",
    "experience": "15+",
    "size": "100+",
    "salary": "$120,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Architect",
    "skills": "Java, Swift, Python, machine learning, JavaScript, etc.",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Mathematics with Computer Science"
  },
  {
    "Timestamp": "12/6/2017 13:59:44",
    "experience": "2-4",
    "size": "100+",
    "salary": "$60,000.00",
    "happy": 5,
    "gender": "Male",
    "position": ".net developer",
    "skills": "C#",
    "work": "I work remotely",
    "education": "Masters",
    "degree": ""
  },
  {
    "Timestamp": "12/6/2017 16:15:09",
    "experience": "15+",
    "size": "100+",
    "salary": "$60,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Software Developer",
    "skills": "C#, Javascript, WPF, SQL",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "12/6/2017 17:56:29",
    "experience": "8-10",
    "size": "100+",
    "salary": "$120,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Dept Head",
    "skills": "Many",
    "work": "Work at a company in or around Cincinnati",
    "education": "Some college",
    "degree": ""
  },
  {
    "Timestamp": "12/7/2017 10:37:58",
    "experience": "10-15",
    "size": "10-50",
    "salary": "$115,000.00",
    "happy": 5,
    "gender": "Male",
    "position": "Developer",
    "skills": "Ruby, Javascript, Elixir",
    "work": "Work at a company in or around Cincinnati",
    "education": "High School",
    "degree": ""
  },
  {
    "Timestamp": "12/7/2017 11:51:57",
    "experience": "10-15",
    "size": "100+",
    "salary": "$86,000.00",
    "happy": 3,
    "gender": "Male",
    "position": "Software Developer",
    "skills": "Java, Bootstrap, Spring",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Computer Science"
  },
  {
    "Timestamp": "12/7/2017 17:15:56",
    "experience": "2-4",
    "size": "100+",
    "salary": "$60,000.00",
    "happy": 4,
    "gender": "Female",
    "position": "Consultant",
    "skills": "Javascript, React, CSS, Node",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "Graphic Design"
  },
  {
    "Timestamp": "12/7/2017 21:01:48",
    "experience": "0-1",
    "size": "10-50",
    "salary": "$55,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Integration Engineer",
    "skills": "Javascipt, Java, Python, SQL, Mirth",
    "work": "Work at a company in or around Cincinnati",
    "education": "Bachelors",
    "degree": "VCD: Animation, Illustration"
  },
  {
    "Timestamp": "12/11/2017 16:51:41",
    "experience": "10-15",
    "size": "50-100",
    "salary": "$125,000.00",
    "happy": 4,
    "gender": "Male",
    "position": "Senior Software Engineer & Cloud Architect",
    "skills": "Professional full-stack development in most primary languages.",
    "work": "Work at a company in or around Cincinnati",
    "education": "High School",
    "degree": ""
  },
  {
    "Timestamp": "12/15/2017 15:02:37",
    "experience": "15+",
    "size": "100+",
    "salary": "$102,000.00",
    "happy": 3,
    "gender": "Male",
    "position": "Senior Software Engineer",
    "skills": "C, C++, Python, JavaScript, AngularJS, Perl, Java, Couchbase, Elasticsearch, SQL, HTML 5, Bash",
    "work": "Work at a company in or around Cincinnati",
    "education": "Masters",
    "degree": "Information Systems"
  }
 ]

 export default data;